#pragma once

#include "msxgl.h"
#include "color.h"

#include "level1_floor_tile.h"
#include "level1_wall_tiles.h"

#define LEVEL1_TILESET_COUNT (LEVEL1_FLOOR_TILE_COUNT + LEVEL1_WALL_TILE_COUNT)
#define LEVEL1_TILESET_SIZE  (LEVEL1_TILESET_COUNT * 8)

/*
Global tile order in VRAM / tile map:

0  -> floor TL
1  -> floor TR
2  -> floor BL
3  -> floor BR

4  -> indestructible TL
5  -> indestructible TR
6  -> indestructible BL
7  -> indestructible BR

8  -> destructible TL
9  -> destructible TR
10 -> destructible BL
11 -> destructible BR
*/

#define LEVEL1_TILESET_FLOOR_TL              0
#define LEVEL1_TILESET_FLOOR_TR              1
#define LEVEL1_TILESET_FLOOR_BL              2
#define LEVEL1_TILESET_FLOOR_BR              3

#define LEVEL1_TILESET_INDESTRUCTIBLE_TL     4
#define LEVEL1_TILESET_INDESTRUCTIBLE_TR     5
#define LEVEL1_TILESET_INDESTRUCTIBLE_BL     6
#define LEVEL1_TILESET_INDESTRUCTIBLE_BR     7

#define LEVEL1_TILESET_DESTRUCTIBLE_TL       8
#define LEVEL1_TILESET_DESTRUCTIBLE_TR       9
#define LEVEL1_TILESET_DESTRUCTIBLE_BL       10
#define LEVEL1_TILESET_DESTRUCTIBLE_BR       11

static const u8 g_Level1TilePatterns[LEVEL1_TILESET_SIZE] =
{
    // =========================================================
    // FLOOR 2x2
    // =========================================================
    0x00, 0x08, 0x14, 0x00, 0x40, 0x20, 0x00, 0x00,
    0x00, 0x10, 0x28, 0x00, 0x02, 0x04, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x02, 0x00, 0x14, 0x08, 0x00,
    0x00, 0x00, 0x80, 0x40, 0x00, 0x28, 0x10, 0x00,

    // =========================================================
// INDESTRUCTIBLE 2x2
// yellow block with black border and 4 black dots
// =========================================================
0xFF, 0x81, 0x81, 0x81, 0x89, 0x81, 0x81, 0xFF,
0xFF, 0x81, 0x81, 0x81, 0x91, 0x81, 0x81, 0xFF,
0xFF, 0x81, 0x81, 0x89, 0x81, 0x81, 0x81, 0xFF,
0xFF, 0x81, 0x81, 0x91, 0x81, 0x81, 0x81, 0xFF,

    // =========================================================
// DESTRUCTIBLE 2x2
// closer to Bomb Mania C64: dark mortar + reddish brick
// =========================================================
0xFF, 0x80, 0xB4, 0x88, 0xFF, 0x80, 0xA4, 0x90,
0xFF, 0x01, 0x2D, 0x11, 0xFF, 0x01, 0x25, 0x09,
0xFF, 0x80, 0x94, 0xA0, 0xFF, 0x80, 0xB4, 0x88,
0xFF, 0x01, 0x29, 0x05, 0xFF, 0x01, 0x2D, 0x11,
};

static const u8 g_Level1TileColors[LEVEL1_TILESET_SIZE] =
{
    // =========================================================
    // FLOOR 2x2
    // =========================================================
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),

    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),

    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),

    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),

    // =========================================================
// INDESTRUCTIBLE 2x2
// foreground = black
// background = light yellow
// =========================================================
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),

COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),

COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),

COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_YELLOW),

    // =========================================================
// DESTRUCTIBLE 2x2
// dark mortar + pink/red body
// =========================================================
COLOR_MERGE(COLOR_BLACK, COLOR_DARK_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_DARK_RED, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_DARK_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_DARK_RED, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),

COLOR_MERGE(COLOR_BLACK, COLOR_DARK_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_DARK_RED, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_DARK_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_DARK_RED, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),

COLOR_MERGE(COLOR_BLACK, COLOR_DARK_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_DARK_RED, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_DARK_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_DARK_RED, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),

COLOR_MERGE(COLOR_BLACK, COLOR_DARK_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_DARK_RED, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_DARK_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_DARK_RED, COLOR_LIGHT_RED),
COLOR_MERGE(COLOR_BLACK, COLOR_LIGHT_RED),
};
