#pragma once

#include "msxgl.h"

#include "level1_floor_tile.h"
#include "level1_wall_tiles.h"

#define LEVEL1_TILESET_COUNT (LEVEL1_FLOOR_TILE_COUNT + LEVEL1_WALL_TILE_COUNT)
#define LEVEL1_TILESET_SIZE  (LEVEL1_TILESET_COUNT * 8)

// Tile order:
// 239 -> floor
// 240 -> indestructible wall
// 241 -> destructible wall
static const u8 g_Level1TilePatterns[LEVEL1_TILESET_SIZE] =
{
    0x00, 0x08, 0x14, 0x00, 0x41, 0x22, 0x00, 0x00,

    0xFF, 0xC3, 0x81, 0xA5, 0x81, 0xA5, 0xC3, 0xFF,
    0xFE, 0x54, 0xBA, 0x10, 0xEF, 0x28, 0xD6, 0x7C,
};

static const u8 g_Level1TileColors[LEVEL1_TILESET_SIZE] =
{
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_LIGHT_GREEN, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),
    COLOR_MERGE(COLOR_GRAY, COLOR_WHITE),

    COLOR_MERGE(COLOR_DARK_YELLOW, COLOR_LIGHT_YELLOW),
    COLOR_MERGE(COLOR_DARK_YELLOW, COLOR_LIGHT_YELLOW),
    COLOR_MERGE(COLOR_DARK_YELLOW, COLOR_LIGHT_YELLOW),
    COLOR_MERGE(COLOR_DARK_YELLOW, COLOR_LIGHT_YELLOW),
    COLOR_MERGE(COLOR_DARK_YELLOW, COLOR_LIGHT_YELLOW),
    COLOR_MERGE(COLOR_DARK_YELLOW, COLOR_LIGHT_YELLOW),
    COLOR_MERGE(COLOR_DARK_YELLOW, COLOR_LIGHT_YELLOW),
    COLOR_MERGE(COLOR_DARK_YELLOW, COLOR_LIGHT_YELLOW),

    COLOR_MERGE(COLOR_GRAY, COLOR_BLACK),
    COLOR_MERGE(COLOR_LIGHT_RED, COLOR_BLACK),
    COLOR_MERGE(COLOR_GRAY, COLOR_BLACK),
    COLOR_MERGE(COLOR_LIGHT_RED, COLOR_BLACK),
    COLOR_MERGE(COLOR_GRAY, COLOR_BLACK),
    COLOR_MERGE(COLOR_LIGHT_RED, COLOR_BLACK),
    COLOR_MERGE(COLOR_GRAY, COLOR_BLACK),
    COLOR_MERGE(COLOR_DARK_RED, COLOR_BLACK),
};
